// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTagToNote(arg1, arg2) {
  return window['go']['main']['App']['AddTagToNote'](arg1, arg2);
}

export function BatchAddTagToNotes(arg1, arg2) {
  return window['go']['main']['App']['BatchAddTagToNotes'](arg1, arg2);
}

export function BatchDeleteNotes(arg1) {
  return window['go']['main']['App']['BatchDeleteNotes'](arg1);
}

export function ChangePassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2, arg3);
}

export function CreateBackup() {
  return window['go']['main']['App']['CreateBackup']();
}

export function CreateNote(arg1, arg2) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2);
}

export function CreateNotebook(arg1, arg2) {
  return window['go']['main']['App']['CreateNotebook'](arg1, arg2);
}

export function CreateSmartView(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSmartView'](arg1, arg2, arg3);
}

export function CreateTag(arg1, arg2) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteNotebook(arg1) {
  return window['go']['main']['App']['DeleteNotebook'](arg1);
}

export function DeleteSmartView(arg1) {
  return window['go']['main']['App']['DeleteSmartView'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function ExportNoteAsMarkdown(arg1) {
  return window['go']['main']['App']['ExportNoteAsMarkdown'](arg1);
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetNoteHistory(arg1) {
  return window['go']['main']['App']['GetNoteHistory'](arg1);
}

export function GetPasswordHint() {
  return window['go']['main']['App']['GetPasswordHint']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSmartView(arg1) {
  return window['go']['main']['App']['GetSmartView'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportBackupWithKey(arg1) {
  return window['go']['main']['App']['ImportBackupWithKey'](arg1);
}

export function ImportMarkdown() {
  return window['go']['main']['App']['ImportMarkdown']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function ListDeletedNotes() {
  return window['go']['main']['App']['ListDeletedNotes']();
}

export function ListNotebooks() {
  return window['go']['main']['App']['ListNotebooks']();
}

export function ListNotes() {
  return window['go']['main']['App']['ListNotes']();
}

export function ListNotesPaginated(arg1, arg2) {
  return window['go']['main']['App']['ListNotesPaginated'](arg1, arg2);
}

export function ListSmartViews() {
  return window['go']['main']['App']['ListSmartViews']();
}

export function ListTags() {
  return window['go']['main']['App']['ListTags']();
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function MigrateOldNotes() {
  return window['go']['main']['App']['MigrateOldNotes']();
}

export function RemoveTagFromNote(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromNote'](arg1, arg2);
}

export function ReorderNotebooks(arg1) {
  return window['go']['main']['App']['ReorderNotebooks'](arg1);
}

export function ReorderNotes(arg1) {
  return window['go']['main']['App']['ReorderNotes'](arg1);
}

export function ResetPasswordWithDataKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResetPasswordWithDataKey'](arg1, arg2, arg3);
}

export function RestoreBackup() {
  return window['go']['main']['App']['RestoreBackup']();
}

export function RestoreNote(arg1) {
  return window['go']['main']['App']['RestoreNote'](arg1);
}

export function RestoreNoteFromHistory(arg1, arg2) {
  return window['go']['main']['App']['RestoreNoteFromHistory'](arg1, arg2);
}

export function SetNoteNotebook(arg1, arg2) {
  return window['go']['main']['App']['SetNoteNotebook'](arg1, arg2);
}

export function SetNotePinned(arg1, arg2) {
  return window['go']['main']['App']['SetNotePinned'](arg1, arg2);
}

export function SetNotebookPinned(arg1, arg2) {
  return window['go']['main']['App']['SetNotebookPinned'](arg1, arg2);
}

export function SetNotesNotebook(arg1, arg2) {
  return window['go']['main']['App']['SetNotesNotebook'](arg1, arg2);
}

export function SetupPassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetupPassword'](arg1, arg2, arg3);
}

export function SoftDeleteNote(arg1) {
  return window['go']['main']['App']['SoftDeleteNote'](arg1);
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function UpdateActivity() {
  return window['go']['main']['App']['UpdateActivity']();
}

export function UpdateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3);
}

export function UpdateNotebook(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateNotebook'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSettings'](arg1, arg2, arg3);
}

export function UpdateSmartView(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSmartView'](arg1, arg2, arg3, arg4);
}

export function UpdateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2, arg3);
}

export function VerifyDataKey(arg1) {
  return window['go']['main']['App']['VerifyDataKey'](arg1);
}
