// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {attachments} from '../models';
import {notes} from '../models';
import {notebooks} from '../models';
import {smartviews} from '../models';
import {tags} from '../models';
import {todos} from '../models';
import {database} from '../models';
import {core} from '../models';

export function AddTagToNote(arg1:string,arg2:string):Promise<void>;

export function AttachAttachmentToNote(arg1:string,arg2:string):Promise<void>;

export function BatchAddTagToNotes(arg1:Array<string>,arg2:string):Promise<void>;

export function BatchDeleteNotes(arg1:Array<string>):Promise<void>;

export function ChangePassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateBackup():Promise<string>;

export function CreateImageFromDataURL(arg1:string,arg2:string,arg3:string):Promise<attachments.Attachment>;

export function CreateNote(arg1:string,arg2:string):Promise<notes.Note>;

export function CreateNotebook(arg1:string,arg2:string):Promise<notebooks.Notebook>;

export function CreateSmartView(arg1:string,arg2:string,arg3:smartviews.Filter):Promise<smartviews.SmartView>;

export function CreateTag(arg1:string,arg2:string):Promise<tags.Tag>;

export function CreateTodo(arg1:string,arg2:string,arg3:string):Promise<todos.Todo>;

export function CreateTodoSubtask(arg1:string,arg2:string):Promise<todos.Subtask>;

export function DeleteAttachment(arg1:string):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function DeleteNotebook(arg1:string):Promise<void>;

export function DeleteSmartView(arg1:string):Promise<void>;

export function DeleteTag(arg1:string):Promise<void>;

export function DeleteTodo(arg1:string):Promise<void>;

export function DeleteTodoSubtask(arg1:string):Promise<void>;

export function DetachAttachmentFromNote(arg1:string,arg2:string):Promise<void>;

export function ExportNoteAsMarkdown(arg1:string):Promise<string>;

export function GenerateDataKey():Promise<string>;

export function GetAttachmentDataURL(arg1:string):Promise<string>;

export function GetAttachmentThumbnailDataURL(arg1:string):Promise<string>;

export function GetDataDir():Promise<string>;

export function GetNote(arg1:string):Promise<notes.Note>;

export function GetNoteHistory(arg1:string):Promise<Array<notes.Note>>;

export function GetPasswordHint():Promise<string>;

export function GetSettings():Promise<database.Settings>;

export function GetSmartView(arg1:string):Promise<smartviews.SmartView>;

export function GetTodo(arg1:string):Promise<todos.Todo>;

export function GetVersion():Promise<string>;

export function ImportBackupWithKey(arg1:string):Promise<number>;

export function ImportImage(arg1:string):Promise<attachments.Attachment>;

export function ImportMarkdown():Promise<notes.Note>;

export function IsFirstRun():Promise<boolean>;

export function IsUnlocked():Promise<boolean>;

export function ListAttachments():Promise<Array<attachments.Attachment>>;

export function ListDeletedAttachments():Promise<Array<attachments.Attachment>>;

export function ListDeletedNotes():Promise<Array<notes.Note>>;

export function ListNotebooks():Promise<Array<notebooks.Notebook>>;

export function ListNotes():Promise<Array<notes.Note>>;

export function ListNotesPaginated(arg1:number,arg2:number):Promise<notes.ListResult>;

export function ListSmartViews():Promise<Array<smartviews.SmartView>>;

export function ListTags():Promise<Array<tags.Tag>>;

export function ListTodos():Promise<Array<todos.Todo>>;

export function Lock():Promise<void>;

export function MigrateOldNotes():Promise<number>;

export function RemoveTagFromNote(arg1:string,arg2:string):Promise<void>;

export function ReorderNotebooks(arg1:Array<string>):Promise<void>;

export function ReorderNotes(arg1:Array<string>):Promise<void>;

export function SearchNotes(arg1:string):Promise<Array<notes.Note>>;

export function ResetPasswordWithDataKey(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestoreAttachment(arg1:string):Promise<void>;

export function RestoreBackup():Promise<void>;

export function RestoreNote(arg1:string):Promise<void>;

export function RestoreNoteFromHistory(arg1:string,arg2:string):Promise<notes.Note>;

export function SetAttachmentFavorite(arg1:string,arg2:boolean):Promise<void>;

export function SetNoteNotebook(arg1:string,arg2:any):Promise<void>;

export function SetNotePinned(arg1:string,arg2:boolean):Promise<void>;

export function SetNotebookPinned(arg1:string,arg2:boolean):Promise<void>;

export function SetNotesNotebook(arg1:Array<string>,arg2:any):Promise<void>;

export function SetTodoCompleted(arg1:string,arg2:boolean):Promise<todos.Todo>;

export function SetTodoSubtaskCompleted(arg1:string,arg2:boolean):Promise<todos.Subtask>;

export function SetupPassword(arg1:string,arg2:string,arg3:string):Promise<core.SetupResult>;

export function SoftDeleteAttachment(arg1:string):Promise<void>;

export function SoftDeleteNote(arg1:string):Promise<void>;

export function Unlock(arg1:string):Promise<boolean>;

export function UpdateActivity():Promise<void>;

export function UpdateNote(arg1:string,arg2:string,arg3:string):Promise<notes.Note>;

export function UpdateNotebook(arg1:string,arg2:string,arg3:string):Promise<notebooks.Notebook>;

export function UpdateSettings(arg1:number,arg2:boolean,arg3:boolean):Promise<void>;

export function UpdateSmartView(arg1:string,arg2:string,arg3:string,arg4:smartviews.Filter):Promise<smartviews.SmartView>;

export function UpdateTag(arg1:string,arg2:string,arg3:string):Promise<tags.Tag>;

export function UpdateTodo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<todos.Todo>;

export function UpdateTodoSubtask(arg1:string,arg2:string):Promise<todos.Subtask>;

export function VerifyDataKey(arg1:string):Promise<boolean>;
